services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - ./service-account-key.json:/app/service-account-key.json
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
